name: Code Coverage
on: pull_request

jobs:
  coveralls:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate coverage
      run: py.test --cov ./pytest_html_reporter/ unittests/

    - name: Send report to Coveralls
      uses: AndreMiras/coveralls-python-action@v20200413
      with:
        github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
        parallel: true
        parallel-finished: true
        debug: true