name: coverage
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate coverage
      run: py.test --cov ./pytest_html_reporter/ xtests/

    - name: Send report to Coveralls
      uses: AndreMiras/coveralls-python-action@v20200413
      with:
        parallel: true

  coveralls_finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: AndreMiras/coveralls-python-action@v20200413
      with:
        parallel-finished: true