name: Create Pull Request
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: master
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v1.7.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch-suffix: none
          base: master
