on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create report file
        run: date +%s > report.txt
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch-suffix: none
          base: master
